theme: jekyll-theme-cayman
title: Traversable Menu
description: A WCAG/ADA compliant sliding push menu / navigation drawer especially well suited for large menus
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
show_downloads: true
